### ISSUE TITLE
Plugin loader doesn't work on JDK > 11

### ISSUE THREAD

**Issue by phucbaodao** [krlvm/PowerTunnel#55]
i tried running power tunnel v2.0 Preview 2 on ubuntu 20.04 but nothing happens, no UI pops up, i haven't tried with command line, but it doesn't seem to work, i use use java 11

**Comment by krlvm** [comment]
Does it produce any output in terminal?

**Comment by phucbaodao** [comment]
i tried starting with terminal and it shows this error message
![Screenshot from 2021-08-24 13-41-02](https://user-images.githubusercontent.com/77871763/130569740-f2951ce9-ed0d-4e0b-b3b2-cc6be7f982b1.jpg)

**Comment by krlvm** [comment]
Thanks for reporting this, the issue was caused by incompatibillity of plugin loader with changes in Java 11, I've released [v2.0-rc3](https://github.com/krlvm/PowerTunnel/releases/tag/v2.0-rc3) with fix, please check does it work for you.

**Comment by phucbaodao** [comment]
I would like to correct one thing: the plugin is still loading, I tried again with terminal and it worked. It seems the problem is with my machine, but the UI still doesn't work.

**Comment by krlvm** [comment]
Do you still see the bootstrap error like on screenshot or you just don't see the UI?

**Comment by phucbaodao** [comment]
oh i just realized you fixed it that's why it worked, thanks for your quick support, it's working properly

**Comment by krlvm** [comment]
How exactly? Can you provide a screenshot?

**Comment by phucbaodao** [comment]
i used this command: java -jar PowerTunnel.jar -start and got the result as shown in the picture i tried config proxy on my pc then i tried accessing some blocked websites in my country and i succeeded. but when i try to run using UI nothing happens
![Screenshot from 2021-08-24 20-52-45](https://user-images.githubusercontent.com/77871763/130707400-f8949b8b-306e-4ffc-9a49-6a4d21959d79.png)

**Comment by krlvm** [comment]
The problem is that tray is not supported on your DE and this error is not handled, launch PowerTunnel with option `-disable-tray`.

**Comment by phucbaodao** [comment]
thank you very much

**Comment by krlvm** [comment]
I will fix this in the next release so you will be able just double-click .jar to run (remember that you need to mark it runnable on Linux and associate .jar extension it with Java).
